export const topicsListGroups = [
    {
        title: 'General',
        items: [
            'Business',
            'Career',
            'Health',
            'Travel',
            'Lifestyle',
            'Fashion',
            'Wellness',
            'Fitness',
        ],
    },
    {
        title: 'Sports',
        items: [
            'Football',
            'Basketball',
            'Tennis',
            'Baseball',
            'Golf',
            'Soccer',
            'Swimming',
            'Fitness',
            'Running',
        ],
    },
    {
        title: 'Technology',
        items: [
            'Programming',
            'Web development',
            'Mobile development',
            'Design',
            'Artificial intelligence',
            'Architecture',
            'Data Science',
            'Machine Learning',
            'Blockchain',
        ],
    },
    {
        title: 'Business',
        items: [
            'Marketing',
            'Sales',
            'Finance',
            'Entrepreneurship',
            'Management',
            'Startups',
        ],
    },
    {
        title: 'Science',
        items: [
            'Physics',
            'Chemistry',
            'Biology',
            'Astronomy',
            'Environmental Science',
            'Geology',
            'Meteorology',
            'Psychology',
        ],
    },
    {
        title: 'Entertainment',
        items: [
            'Movies',
            'Music',
            'Gaming',
            'Books',
            'TV Shows',
            'Comics',
            'Theater',
            'Art',
        ],
    },
    {
        title: 'Food',
        items: [
            'Cooking',
            'Nutrition',
            'Restaurant Reviews',
            'Baking',
            'Food Photography',
            'Vegan Recipes',
            'Vegetarian Recipes',
        ],
    },
    {
        title: 'Hobbies',
        items: [
            'Photography',
            'Gardening',
            'DIY Projects',
            'Painting',
            'Sculpture',
            'Collecting',
            'Knitting',
        ],
    },
    {
        title: 'Travel',
        items: [
            'Adventure Travel',
            'Budget Travel',
            'Cultural Experiences',
            'Travel Tips',
            'Solo Travel',
            'Family Travel',
            'Travel Photography',
        ],
    },
];
